#!/bin/bash

# Run Pylint
# (for information only, any errors don't affect the Travis result)

pylint --use-ignore-patch=y openphoto
pylint --use-ignore-patch=y tests

# Create a config file containing the test host's secrets

CONFIG_DIR=~/.config/openphoto
CONFIG_FILE=$CONFIG_DIR/test

mkdir ~/.config
mkdir $CONFIG_DIR

echo "host = $OP_HOST" >> $CONFIG_FILE
echo "consumerKey = $OP_CONSUMER_KEY" >> $CONFIG_FILE
echo "consumerSecret = $OP_CONSUMER_SECRET" >> $CONFIG_FILE
echo "token = $OP_TOKEN" >> $CONFIG_FILE
echo "tokenSecret = $OP_TOKEN_SECRET" >> $CONFIG_FILE

# Run the tests

tox -e py27
